"""add commercial schema

Revision ID: 0002_commercial_schema
Revises: 0001_baseline
Create Date: 2026-09-17 23:56:15.737154

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_commercial_schema"
down_revision: str | Sequence[str] | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "businesses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("gstin", sa.String(length=32), nullable=True),
        sa.Column("billing_address", sa.String(length=1000), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Kolkata", nullable=False),
        sa.Column("quote_validity_minutes", sa.Integer(), nullable=True),
        sa.Column("approval_required_for_all", sa.Boolean(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name="ck_businesses_currency_inr"),
        sa.CheckConstraint(
            "quote_validity_minutes IS NULL OR quote_validity_minutes > 0",
            name="ck_businesses_quote_validity_positive",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "buyers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("whatsapp_e164", sa.String(length=32), nullable=True),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("billing_address", sa.String(length=1000), nullable=True),
        sa.Column("gstin", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_name IS NOT NULL OR whatsapp_e164 IS NOT NULL",
            name="ck_buyers_identity_present",
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "id", name="uq_buyers_business_id_id"),
    )
    op.create_index(
        "ix_buyers_business_whatsapp", "buyers", ["business_id", "whatsapp_e164"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="PROCESSING", nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_reference", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("state IN ('PROCESSING', 'COMPLETED')", name="ck_idempotency_state"),
        sa.CheckConstraint(
            "response_status IS NULL OR response_status BETWEEN 100 AND 599",
            name="ck_idempotency_response_status",
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "action", "key", name="uq_idempotency_business_action_key"
        ),
    )
    op.create_table(
        "invoice_sequences",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("calendar_year", sa.Integer(), nullable=False),
        sa.Column("next_value", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("calendar_year BETWEEN 2000 AND 9999", name="ck_invoice_sequences_year"),
        sa.CheckConstraint("next_value > 0", name="ck_invoice_sequences_next_positive"),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("business_id", "calendar_year"),
    )
    op.create_table(
        "pricing_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("max_discount_bps", sa.Integer(), nullable=False),
        sa.Column("min_margin_bps", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name="ck_pricing_rules_effective_range",
        ),
        sa.CheckConstraint(
            "max_discount_bps BETWEEN 0 AND 10000", name="ck_pricing_rules_discount_bps"
        ),
        sa.CheckConstraint(
            "min_margin_bps BETWEEN 0 AND 10000", name="ck_pricing_rules_margin_bps"
        ),
        sa.CheckConstraint("version > 0", name="ck_pricing_rules_version_positive"),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "id", "version", name="uq_pricing_rules_business_id_version"
        ),
        sa.UniqueConstraint("business_id", "id", name="uq_pricing_rules_business_id_id"),
        sa.UniqueConstraint("business_id", "version", name="uq_pricing_rules_business_version"),
    )
    op.create_index(
        "uq_pricing_rules_one_active_per_business",
        "pricing_rules",
        ["business_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("normalized_sku", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("sellable_unit", sa.String(length=32), nullable=False),
        sa.Column("stock_unit", sa.String(length=32), nullable=False),
        sa.Column("pack_size", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("indivisible", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("cost_unit_paise", sa.BigInteger(), nullable=False),
        sa.Column("base_unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("gst_rate_bps", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("base_unit_price_paise > 0", name="ck_products_price_positive"),
        sa.CheckConstraint("cost_unit_paise >= 0", name="ck_products_cost_nonnegative"),
        sa.CheckConstraint("gst_rate_bps BETWEEN 0 AND 10000", name="ck_products_gst_rate"),
        sa.CheckConstraint("pack_size > 0", name="ck_products_pack_size_positive"),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "id", name="uq_products_business_id_id"),
        sa.UniqueConstraint(
            "business_id", "normalized_sku", name="uq_products_business_normalized_sku"
        ),
        sa.UniqueConstraint("business_id", "sku", name="uq_products_business_sku"),
    )
    op.create_index(
        "ix_products_business_normalized_name",
        "products",
        ["business_id", "normalized_name"],
        unique=False,
    )
    op.create_table(
        "quote_lineages",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("latest_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("latest_version >= 0", name="ck_quote_lineages_latest_version"),
        sa.CheckConstraint("length(trim(run_id)) > 0", name="ck_quote_lineages_run_nonempty"),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("business_id", "run_id"),
    )
    op.create_table(
        "inventory",
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("reorder_threshold", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("on_hand_qty >= 0", name="ck_inventory_on_hand_nonnegative"),
        sa.CheckConstraint(
            "reorder_threshold IS NULL OR reorder_threshold >= 0",
            name="ck_inventory_reorder_threshold_nonnegative",
        ),
        sa.CheckConstraint("version > 0", name="ck_inventory_version_positive"),
        sa.ForeignKeyConstraint(
            ["business_id", "product_id"],
            ["products.business_id", "products.id"],
            name="fk_inventory_business_product",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("business_id", "product_id"),
    )
    op.create_table(
        "product_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("alias_text", sa.String(length=255), nullable=False),
        sa.Column("normalized_alias", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id", "product_id"],
            ["products.business_id", "products.id"],
            name="fk_product_aliases_business_product",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id",
            "normalized_alias",
            "product_id",
            name="uq_product_aliases_business_alias_product",
        ),
    )
    op.create_index(
        "ix_product_aliases_business_product",
        "product_aliases",
        ["business_id", "product_id"],
        unique=False,
    )
    op.create_table(
        "product_substitutes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("substitute_product_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "product_id <> substitute_product_id", name="ck_product_substitutes_not_self"
        ),
        sa.CheckConstraint("rank > 0", name="ck_product_substitutes_rank_positive"),
        sa.ForeignKeyConstraint(
            ["business_id", "product_id"],
            ["products.business_id", "products.id"],
            name="fk_product_substitutes_business_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "substitute_product_id"],
            ["products.business_id", "products.id"],
            name="fk_product_substitutes_business_substitute",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "product_id", "substitute_product_id", name="uq_product_substitutes_pair"
        ),
    )
    op.create_index(
        "ix_product_substitutes_business_product_rank",
        "product_substitutes",
        ["business_id", "product_id", "rank"],
        unique=False,
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("quote_version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pricing_rule_id", sa.Uuid(), nullable=False),
        sa.Column("pricing_rule_version", sa.Integer(), nullable=False),
        sa.Column("policy_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tax_context_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="DRAFT", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("subtotal_paise", sa.BigInteger(), nullable=False),
        sa.Column("tax_paise", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("approval_required", sa.Boolean(), nullable=False),
        sa.Column(
            "approval_satisfied", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("approval_id", sa.String(length=160), nullable=True),
        sa.Column("approval_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("acceptance_id", sa.String(length=160), nullable=True),
        sa.Column("acceptance_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name="ck_quotes_currency_inr"),
        sa.CheckConstraint(
            "status <> 'ACCEPTED' OR "
            "(acceptance_id IS NOT NULL AND acceptance_evidence IS NOT NULL "
            "AND accepted_at IS NOT NULL)",
            name="ck_quotes_acceptance_evidence",
        ),
        sa.CheckConstraint(
            "status NOT IN ('GENERATED', 'ACCEPTED') OR generated_at IS NOT NULL",
            name="ck_quotes_generated_timestamp",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'GENERATED', 'ACCEPTED', 'EXPIRED', 'CANCELLED')",
            name="ck_quotes_status",
        ),
        sa.CheckConstraint(
            "status NOT IN ('GENERATED', 'ACCEPTED') OR "
            "NOT approval_required OR approval_satisfied",
            name="ck_quotes_required_approval_satisfied",
        ),
        sa.CheckConstraint(
            "NOT approval_satisfied OR (approval_id IS NOT NULL AND approval_evidence IS NOT NULL)",
            name="ck_quotes_approval_evidence",
        ),
        sa.CheckConstraint("length(trim(run_id)) > 0", name="ck_quotes_run_nonempty"),
        sa.CheckConstraint("quote_version > 0", name="ck_quotes_version_positive"),
        sa.CheckConstraint(
            "subtotal_paise >= 0 AND tax_paise >= 0 AND total_paise > 0",
            name="ck_quotes_amounts_positive",
        ),
        sa.CheckConstraint("total_paise = subtotal_paise + tax_paise", name="ck_quotes_total_sum"),
        sa.ForeignKeyConstraint(
            ["business_id", "buyer_id"],
            ["buyers.business_id", "buyers.id"],
            name="fk_quotes_business_buyer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "pricing_rule_id", "pricing_rule_version"],
            ["pricing_rules.business_id", "pricing_rules.id", "pricing_rules.version"],
            name="fk_quotes_business_pricing_rule_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "run_id"],
            ["quote_lineages.business_id", "quote_lineages.run_id"],
            name="fk_quotes_business_run_lineage",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "acceptance_id", name="uq_quotes_business_acceptance"),
        sa.UniqueConstraint("business_id", "approval_id", name="uq_quotes_business_approval"),
        sa.UniqueConstraint(
            "business_id", "id", "quote_version", name="uq_quotes_business_id_version"
        ),
        sa.UniqueConstraint(
            "business_id",
            "id",
            "quote_version",
            "run_id",
            name="uq_quotes_business_id_version_run",
        ),
        sa.UniqueConstraint("business_id", "id", name="uq_quotes_business_id_id"),
        sa.UniqueConstraint(
            "business_id", "run_id", "quote_version", name="uq_quotes_business_run_version"
        ),
    )
    op.create_index(
        "ix_quotes_business_expires", "quotes", ["business_id", "expires_at"], unique=False
    )
    op.create_index("ix_quotes_business_status", "quotes", ["business_id", "status"], unique=False)
    op.create_index(
        "uq_quotes_business_run_current",
        "quotes",
        ["business_id", "run_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("quote_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="CREATED", nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("provider_account_key", sa.String(length=160), nullable=False),
        sa.Column("provider_reference_id", sa.String(length=160), nullable=False),
        sa.Column("provider_link_id", sa.String(length=160), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=160), nullable=True),
        sa.Column("provider_order_id", sa.String(length=160), nullable=True),
        sa.Column("payment_url", sa.String(length=1000), nullable=True),
        sa.Column("link_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "reconciliation_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name="ck_payments_currency_inr"),
        sa.CheckConstraint(
            "status <> 'PAID' OR (provider_payment_id IS NOT NULL AND paid_at IS NOT NULL)",
            name="ck_payments_paid_provider_id",
        ),
        sa.CheckConstraint(
            "status <> 'PENDING' OR (provider_link_id IS NOT NULL AND payment_url IS NOT NULL)",
            name="ck_payments_pending_link",
        ),
        sa.CheckConstraint(
            "status IN ('CREATED', 'PENDING', 'PAID', 'FAILED', 'EXPIRED', 'CANCELLED')",
            name="ck_payments_status",
        ),
        sa.CheckConstraint("amount_paise > 0", name="ck_payments_amount_positive"),
        sa.CheckConstraint("length(trim(run_id)) > 0", name="ck_payments_run_nonempty"),
        sa.CheckConstraint("quote_version > 0", name="ck_payments_quote_version_positive"),
        sa.ForeignKeyConstraint(
            ["business_id", "quote_id", "quote_version", "run_id"],
            ["quotes.business_id", "quotes.id", "quotes.quote_version", "quotes.run_id"],
            name="fk_payments_business_quote_version_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "id", "provider_account_key", name="uq_payments_business_id_account"
        ),
        sa.UniqueConstraint(
            "business_id", "id", "quote_id", "run_id", name="uq_payments_business_id_quote_run"
        ),
        sa.UniqueConstraint("business_id", "id", name="uq_payments_business_id_id"),
        sa.UniqueConstraint(
            "provider_account_key", "provider_link_id", name="uq_payments_provider_link"
        ),
        sa.UniqueConstraint(
            "provider_account_key", "provider_payment_id", name="uq_payments_provider_payment"
        ),
        sa.UniqueConstraint(
            "provider_account_key", "provider_reference_id", name="uq_payments_provider_reference"
        ),
    )
    op.create_index(
        "ix_payments_business_quote_version",
        "payments",
        ["business_id", "quote_id", "quote_version"],
        unique=False,
    )
    op.create_index(
        "uq_payments_one_active_or_paid_per_quote",
        "payments",
        ["business_id", "quote_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('CREATED', 'PENDING', 'PAID')"),
    )
    op.create_table(
        "quote_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku_snapshot", sa.String(length=80), nullable=False),
        sa.Column("name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("sellable_unit_snapshot", sa.String(length=32), nullable=False),
        sa.Column("stock_unit_snapshot", sa.String(length=32), nullable=False),
        sa.Column("pack_size", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("cost_unit_paise", sa.BigInteger(), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("gross_paise", sa.BigInteger(), nullable=False),
        sa.Column("discount_bps", sa.Integer(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), nullable=False),
        sa.Column("taxable_paise", sa.BigInteger(), nullable=False),
        sa.Column("gst_rate_bps", sa.Integer(), nullable=False),
        sa.Column("tax_paise", sa.BigInteger(), nullable=False),
        sa.Column("line_total_paise", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "cost_unit_paise >= 0 AND unit_price_paise > 0 AND gross_paise > 0",
            name="ck_quote_items_prices",
        ),
        sa.CheckConstraint(
            "discount_bps BETWEEN 0 AND 10000 AND gst_rate_bps BETWEEN 0 AND 10000",
            name="ck_quote_items_rates",
        ),
        sa.CheckConstraint(
            "discount_paise >= 0 AND discount_paise <= gross_paise",
            name="ck_quote_items_discount_amount",
        ),
        sa.CheckConstraint("line_no > 0", name="ck_quote_items_line_positive"),
        sa.CheckConstraint(
            "line_total_paise = taxable_paise + tax_paise", name="ck_quote_items_total_sum"
        ),
        sa.CheckConstraint("pack_size > 0", name="ck_quote_items_pack_size_positive"),
        sa.CheckConstraint("quantity > 0", name="ck_quote_items_quantity_positive"),
        sa.CheckConstraint("tax_paise >= 0", name="ck_quote_items_tax_nonnegative"),
        sa.CheckConstraint(
            "taxable_paise = gross_paise - discount_paise AND taxable_paise > 0",
            name="ck_quote_items_taxable",
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "product_id"],
            ["products.business_id", "products.id"],
            name="fk_quote_items_business_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "quote_id"],
            ["quotes.business_id", "quotes.id"],
            name="fk_quote_items_business_quote",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "quote_id", "line_no", name="uq_quote_items_line"),
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("movement_key", sa.String(length=160), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("resulting_on_hand_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity_delta <> 0", name="ck_stock_movements_delta_nonzero"),
        sa.CheckConstraint(
            "resulting_on_hand_qty >= 0", name="ck_stock_movements_result_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "product_id"],
            ["inventory.business_id", "inventory.product_id"],
            name="fk_stock_movements_business_inventory",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "movement_key", name="uq_stock_movements_business_key"),
    )
    op.create_index(
        "ix_stock_movements_business_product_created",
        "stock_movements",
        ["business_id", "product_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("quote_version", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default="PENDING_ARTIFACT", nullable=False
        ),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_key", sa.String(length=500), nullable=True),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("currency = 'INR'", name="ck_invoices_currency_inr"),
        sa.CheckConstraint(
            "invoice_number ~ '^INV-[0-9]{4}-[0-9]{6}$'", name="ck_invoices_number_format"
        ),
        sa.CheckConstraint(
            "status <> 'GENERATED' OR (artifact_key IS NOT NULL AND "
            "artifact_sha256 IS NOT NULL AND generated_at IS NOT NULL)",
            name="ck_invoices_generated_artifact",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_ARTIFACT', 'GENERATED')", name="ck_invoices_status"
        ),
        sa.CheckConstraint("length(trim(run_id)) > 0", name="ck_invoices_run_nonempty"),
        sa.CheckConstraint("quote_version > 0", name="ck_invoices_quote_version_positive"),
        sa.CheckConstraint("total_paise > 0", name="ck_invoices_total_positive"),
        sa.ForeignKeyConstraint(
            ["business_id", "payment_id", "quote_id", "run_id"],
            ["payments.business_id", "payments.id", "payments.quote_id", "payments.run_id"],
            name="fk_invoices_business_payment_quote_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "quote_id", "quote_version", "run_id"],
            ["quotes.business_id", "quotes.id", "quotes.quote_version", "quotes.run_id"],
            name="fk_invoices_business_quote_version_run",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "invoice_number", name="uq_invoices_business_number"),
        sa.UniqueConstraint("business_id", "payment_id", name="uq_invoices_business_payment"),
        sa.UniqueConstraint("business_id", "quote_id", name="uq_invoices_business_quote"),
    )
    op.create_table(
        "payment_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_account_key", sa.String(length=160), nullable=False),
        sa.Column("provider_event_id", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("safe_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["business_id", "payment_id", "provider_account_key"],
            ["payments.business_id", "payments.id", "payments.provider_account_key"],
            name="fk_payment_events_business_payment_account",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_id", "id", name="uq_payment_events_business_id_id"),
        sa.UniqueConstraint(
            "provider",
            "provider_account_key",
            "provider_event_id",
            name="uq_payment_events_provider_account_event",
        ),
    )
    op.create_index(
        "ix_payment_events_business_payment",
        "payment_events",
        ["business_id", "payment_id"],
        unique=False,
    )
    op.create_table(
        "payment_outbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("business_id", sa.Uuid(), nullable=False),
        sa.Column("payment_event_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=120), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_id", "payment_event_id"],
            ["payment_events.business_id", "payment_events.id"],
            name="fk_payment_outbox_business_event",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "payment_event_id", "topic", name="uq_payment_outbox_event_topic"
        ),
    )
    op.create_index(
        "ix_payment_outbox_unpublished",
        "payment_outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_payment_outbox_unpublished",
        table_name="payment_outbox",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("payment_outbox")
    op.drop_index("ix_payment_events_business_payment", table_name="payment_events")
    op.drop_table("payment_events")
    op.drop_table("invoices")
    op.drop_index("ix_stock_movements_business_product_created", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_table("quote_items")
    op.drop_index(
        "uq_payments_one_active_or_paid_per_quote",
        table_name="payments",
        postgresql_where=sa.text("status IN ('CREATED', 'PENDING', 'PAID')"),
    )
    op.drop_index("ix_payments_business_quote_version", table_name="payments")
    op.drop_table("payments")
    op.drop_index(
        "uq_quotes_business_run_current",
        table_name="quotes",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_index("ix_quotes_business_status", table_name="quotes")
    op.drop_index("ix_quotes_business_expires", table_name="quotes")
    op.drop_table("quotes")
    op.drop_index("ix_product_substitutes_business_product_rank", table_name="product_substitutes")
    op.drop_table("product_substitutes")
    op.drop_index("ix_product_aliases_business_product", table_name="product_aliases")
    op.drop_table("product_aliases")
    op.drop_table("inventory")
    op.drop_table("quote_lineages")
    op.drop_index("ix_products_business_normalized_name", table_name="products")
    op.drop_table("products")
    op.drop_index(
        "uq_pricing_rules_one_active_per_business",
        table_name="pricing_rules",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("pricing_rules")
    op.drop_table("invoice_sequences")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_buyers_business_whatsapp", table_name="buyers")
    op.drop_table("buyers")
    op.drop_table("businesses")
    # ### end Alembic commands ###
